### ISSUE TITLE
Cannot resolve relative files in json-schemas during validation phase

### ISSUE THREAD

**Issue by OlegDokuka** [raml-org/raml-java-parser#310]
## Problem 
No supporting of relative referencing from one json schema to another 

## Library & Spec versions

**Lib**: master
**Spec**: v1.0 

### Project Structure 
myProject
|
|------src
|.........|
|.........\\-------main
|.........|............|
|.........|............\\-------resources
|.........|............|...............|
|.........|............|...............\\------api.raml
|.........|............|...............|
|.........|............|...............\\------schemas
|.........|............|...............|..............|
|.........|............|...............|..............\\------schema1.json
|.........|............|...............|..............\\------schema2.json

`schema1` depends on `schema2`
### Code 
*Api.raml*
```
types:
  MySchema:
    type: !include schemas/schema1.json
#===============================================================
# API resource definitions
#===============================================================
/my:
  description: My URL
  displayName: URL
  /url:
    description: Another
    displayName: Another
    uriParameters: null
    get:
      description: "Get Data"
      queryParameters:
      responses:
        200:
          description: Some Desc
          body:
            application/json:
              type: MySchema
              example: | 
                  [
                    {
                      "id": "1",
                      "reference": "AASDS123123ASDFAS",
                      "dateOfSignature": "2016-10-11T00:00:00Z"
                    },
                    {
                      "id": "2",
                      "reference": "AASDS123123ASDFAS",
                      "dateOfSignature": "2016-06-30T00:00:00Z"
                    },
                    {
                      "id": "3",
                      "reference": "AASDS123123ASDFAS",
                      "dateOfSignature": "2016-07-25T00:00:00Z"
                    }
                  ]
```

*Schema 1.json*
```
{
  "description": "List of data",
  "type": "array",
  "required": [
    "items"
  ],
  "items": {
    "$ref" : "schema2.json"
  }
}
```

*Schema 2.json*
```
{
  "type": "object",
  "properties": {
    "id": {
      "description": "Internal id",
      "type": "string"
    },
    "reference": {
      "description": "Reference User.",
      "type": "string",
      "minLength": 1,
      "maxLength": 35
    },
    "dateOfSignature": {
      "description": "Date of signature",
      "type": "string",
      "format": "date-time"
    }
  },
  "required": [
    "id",
    "reference",
    "dateOfSignature"
  ]
}

```

## Problem Details
So... what I have found... Included `example` section cause additional schema validation during 
`org.raml.v2.internal.impl.v10.phase.ExampleValidationPhase`. During Validation library tries to validate path in `$ref` field
1) `json-schema-core` does not support relative URI ( look at `com.github.fge.jsonschema.core.load.SchemaLoader#get` )
2) To resolve relative path `SchemaLoader` use `com.github.fge.jsonschema.core.load.uri.URITranslator`
3) `URITranslator` configured by `com.github.fge.jsonschema.core.load.configuration.LoadingConfiguration`
4) `LoadingConfiguration` created by `com.github.fge.jsonschema.main.JsonSchemaFactory`
5) `JsonSchemaFactory` created by `org.raml.v2.internal.utils.SchemaGenerator#generateJsonSchema`
6) `generateJsonSchema` create default configuration with no `URITranslators`
7) According to 1-6 we have no chance to resolve relative URI - and that is why we got Exception 

```
if (!ref.isAbsolute())
            throw new ProcessingException(new ProcessingMessage()
                .setMessage(BUNDLE.getMessage("refProcessing.uriNotAbsolute"))
                .putArgument("uri", ref));
```

8) json-schema support list of absolute URI protocols (see `com.github.fge.jsonschema.core.load.configuration.URIDownloadersRegistry`)
9) Supported protocols are http, https, file, ftp, jar, resource 
10) Mentioned protocols such as file, jar, resource make no sense for **json-schema** specification (or even for js-raml-parse for example)  

## Conclusion

So, it looks like missing relative path resolving or way to configure this relative path resolving in json-schema over raml-parser

**Comment by LorenaSoledad** [comment]
Hi @OlegDokuka
Which version of the parser are you using?

**Comment by OlegDokuka** [comment]
Hi @LorenaSoledad. I`m using latest version of plugin

**Comment by OlegDokuka** [comment]
Yesterday I tried to dive deeper into the code of the library, and found that we can provide some information about location of the file for `JsonSchemaFactory` 

**org.raml.v2.internal.utils.SchemaGenerator#generateJsonSchema**
```
public static JsonSchema generateJsonSchema(JsonSchemaExternalType jsonTypeDefinition) throws IOException,
            ProcessingException {
        String includedResourceUri = resolveResourceUriIfIncluded(jsonTypeDefinition);

        JsonNode jsonSchema = JsonLoader.fromString(jsonTypeDefinition.getSchemaValue());
        Node node = NodeUtils.getRootSource(jsonTypeDefinition.getTypeDeclarationNode());


        JsonSchemaFactory factory;
        if (node instanceof SYIncludeNode) {
            SYIncludeNode includeNode = (SYIncludeNode) node;
            String location = ResourcePathUtils.toAbsoluteLocation(node.getStartPosition().getPath(), includeNode
                    .getIncludePath());
            factory =
                    JsonSchemaFactory.newBuilder()
                            .setLoadingConfiguration(
                                    LoadingConfiguration.newBuilder()
                                            .setURITranslatorConfiguration(
                                                    URITranslatorConfiguration.newBuilder()
                                                            .setNamespace("file:" + new File(location).getParent() + 
                                                                    "/")
                                                            .freeze()
                                            )
                                            .freeze()
                            )
                            .freeze();
        } else {
            factory = JsonSchemaFactory.newBuilder().freeze();
        }
//omitted code
```

This workaround looks good, but only when the node type is `SYIncludeNode`, in other words the raml should looks like next 

```
types:
  MySchema:
    type: !include schemas/schema1.json
#===============================================================
# API resource definitions
#===============================================================
/my:
  description: My URL
  displayName: URL
  /url:
    description: Another
    displayName: Another
    uriParameters: null
    get:
      description: "Get Data"
      queryParameters:
      responses:
        200:
          description: Some Desc
          body:
            application/json:
              type: !include schemas/schema1.json
              example: | 
                  [
                    {
                      "id": "1",
                      "reference": "AASDS123123ASDFAS",
                      "dateOfSignature": "2016-10-11T00:00:00Z"
                    },
                    {
                      "id": "2",
                      "reference": "AASDS123123ASDFAS",
                      "dateOfSignature": "2016-06-30T00:00:00Z"
                    },
                    {
                      "id": "3",
                      "reference": "AASDS123123ASDFAS",
                      "dateOfSignature": "2016-07-25T00:00:00Z"
                    }
                  ]
```
otherwise this trick will not work

**Comment by edjannoo** [comment]
I have a similar problem in my project - we have a RAML file that uses `!include` to pull in a JSON schema from a path relative to the RAML file itself (such as `!include schemas/services/service.json`) and the JSON schema uses `$ref` with a relative path (such as `../common/types.json`) to pull in other types. 

We're using the `UrlResourceLoader` to fetch the RAML from an http endpoint and the JSON schemas are available from there too.

I can get this to work if I use an absolute URL for the `$ref` but that's not an adequate solution as it doesn't allow for different versions to be deployed to different environments (test, staging, production)

This needs to be able to resolve relative `$ref` in JSON schema using whichever loader/protocol has been used to fetch the RAML and top level JSON

**Comment by OlegDokuka** [comment]
In my opinion the simplest solution is providing info to `JsonSchemaFactory` like next:
**org.raml.v2.internal.utils.SchemaGenerator#generateJsonSchema**
```java
public static JsonSchema generateJsonSchema(JsonSchemaExternalType jsonTypeDefinition) throws IOException,
            ProcessingException {
        String includedResourceUri = resolveResourceUriIfIncluded(jsonTypeDefinition);

        JsonNode jsonSchema = JsonLoader.fromString(jsonTypeDefinition.getSchemaValue());

        JsonSchemaFactory factory =
                JsonSchemaFactory.newBuilder()
                        .setLoadingConfiguration(
                                LoadingConfiguration.newBuilder()
                                        .setURITranslatorConfiguration(
                                                URITranslatorConfiguration.newBuilder()
                                                        .setNamespace("file:" + new File(jsonTypeDefinition.getSchemaPath()).getParent() + "/")
                                                        .freeze()
                                        )
                                        .freeze()
                        )
                        .freeze();

//omitted code
```

But in this case the relative folder are always being the folder where ***.raml located. But due to specification we should have ability to resolve files from the folder where the operated file are. Right?
Thus, it fills like jsonTypeDefinition.getSchemaPath() should contain absolute path to the json which now are being processed instead path to ***.raml

**Comment by OlegDokuka** [comment]
@LorenaSoledad, @edjannoo FYI. Bug was fixed. Hope the PR would be merged in the nearest future. Description of fix presents in the PR.

**Comment by LorenaSoledad** [comment]
@OlegDokuka, this issue is similar to #277, which was solved in version 1.0.2
We are currently on version 1.0.3, so the last version of the parser should have this problem fixed.

I've created my own test with your files, and its working fine for me.
Please, let me know if you have any news on this.
Thanks

**Comment by OlegDokuka** [comment]
@LorenaSoledad, can you share your test? Because it looks like you miss the part that I described in my PR. Also I added my own test that ensure this bug

**Comment by OlegDokuka** [comment]
yeah, it works, my bad.

**Comment by myhau** [comment]
Hey, for me this was still not working for 1.0 raml.
After debugging it, I've added some useful information here:
https://github.com/raml-org/raml-java-parser/issues/362
